// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw9gghwYr_agyJzMKdKSi42P5aIHcUyIA',
    appId: '1:197098155936:web:2274076b2f00405fc6bec5',
    messagingSenderId: '197098155936',
    projectId: 'smart-fire-alarm-project',
    authDomain: 'smart-fire-alarm-project.firebaseapp.com',
    databaseURL:
        'https://smart-fire-alarm-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-fire-alarm-project.firebasestorage.app',
    measurementId: 'G-X03EGZ3CG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9_RyKcwJZU5AHfJnItu54WpvHWmBlCeo',
    appId: '1:197098155936:android:c0209e799703852ac6bec5',
    messagingSenderId: '197098155936',
    projectId: 'smart-fire-alarm-project',
    databaseURL:
        'https://smart-fire-alarm-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-fire-alarm-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtb_5pNCqGjYXWgfFt1ktiYWzPtNboLU8',
    appId: '1:197098155936:ios:2a3e3972b1f78a90c6bec5',
    messagingSenderId: '197098155936',
    projectId: 'smart-fire-alarm-project',
    databaseURL:
        'https://smart-fire-alarm-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-fire-alarm-project.firebasestorage.app',
    iosBundleId: 'com.example.smartFireAlarmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtb_5pNCqGjYXWgfFt1ktiYWzPtNboLU8',
    appId: '1:197098155936:ios:2a3e3972b1f78a90c6bec5',
    messagingSenderId: '197098155936',
    projectId: 'smart-fire-alarm-project',
    databaseURL:
        'https://smart-fire-alarm-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-fire-alarm-project.firebasestorage.app',
    iosBundleId: 'com.example.smartFireAlarmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw9gghwYr_agyJzMKdKSi42P5aIHcUyIA',
    appId: '1:197098155936:web:eeda0e64b7158c21c6bec5',
    messagingSenderId: '197098155936',
    projectId: 'smart-fire-alarm-project',
    authDomain: 'smart-fire-alarm-project.firebaseapp.com',
    databaseURL:
        'https://smart-fire-alarm-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-fire-alarm-project.firebasestorage.app',
    measurementId: 'G-05TSLJ2805',
  );
}
